
export const WORKER_ADD = "WORKER_ADD"
export const CLIENT_EDIT = "CLIENT_EDIT"
export const CLIENT_ADD_ALL = "CLIENT_ADD_ALL"
export const CLIENT_DELETE = "CLIENT_DELETE"
export const CLIENT_CARD = "CLIENT_CARD"

export const COMMENTS_ADD = "COMMENTS_ADD"
export const COMMENTS_DELETE = "COMMENTS_DELETE"

export const ORDER_ADD = "ORDER_ADD"
export const ORDER_ADD_ALL = "ORDER_ADD_ALL"

//======= 

export const CLIENTS_GET_START = "CLIENT_GET_START"
export const CLIENTS_GET_SUCCESS = "CLIENT_GET_SUCCESS"
export const CLIENTS_GET_ERROR = "CLIENT_GET_ERROR"
